[features]
seeds = false
[programs.localnet]
lendoor = "5eXF5XFaQSffW8JiCR2T5rPvuHjaMx5rjTvsgYmxQDvr"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/ilmoi/.config/solana/play.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
